"""autogenerated by genpy from core/Camera_msgs.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class Camera_msgs(genpy.Message):
  _md5sum = "8e94230b3f39704075111718d57a6c87"
  _type = "core/Camera_msgs"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 center_x
int32 center_y
int32 centroid_x
int32 centroid_y
time time

"""
  __slots__ = ['center_x','center_y','centroid_x','centroid_y','time']
  _slot_types = ['int32','int32','int32','int32','time']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       center_x,center_y,centroid_x,centroid_y,time

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Camera_msgs, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.center_x is None:
        self.center_x = 0
      if self.center_y is None:
        self.center_y = 0
      if self.centroid_x is None:
        self.centroid_x = 0
      if self.centroid_y is None:
        self.centroid_y = 0
      if self.time is None:
        self.time = genpy.Time()
    else:
      self.center_x = 0
      self.center_y = 0
      self.centroid_x = 0
      self.centroid_y = 0
      self.time = genpy.Time()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_4i2I.pack(_x.center_x, _x.center_y, _x.centroid_x, _x.centroid_y, _x.time.secs, _x.time.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.time is None:
        self.time = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.center_x, _x.center_y, _x.centroid_x, _x.centroid_y, _x.time.secs, _x.time.nsecs,) = _struct_4i2I.unpack(str[start:end])
      self.time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_4i2I.pack(_x.center_x, _x.center_y, _x.centroid_x, _x.centroid_y, _x.time.secs, _x.time.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.time is None:
        self.time = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.center_x, _x.center_y, _x.centroid_x, _x.centroid_y, _x.time.secs, _x.time.nsecs,) = _struct_4i2I.unpack(str[start:end])
      self.time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4i2I = struct.Struct("<4i2I")
